---

- name: "POST | AUDITD | Apply auditd template for section 6.3.3.x"
  when: update_audit_template
  ansible.builtin.template:
    src: audit/99_auditd.rules.j2
    dest: /etc/audit/rules.d/99_auditd.rules
    owner: root
    group: root
    mode: 'u-x,go-wx'
  register: discovered_audit_rules_updated
  notify:
    - Auditd rules reload
    - Audit_immutable_fact
    - Restart auditd
    - Set_reboot_required

- name: POST | AUDITD | Set up auditd user logging exceptions
  when: suse15cis_allow_auditd_uid_user_exclusions
  ansible.builtin.template:
    src: audit/98_auditd_exception.rules.j2
    dest: /etc/audit/rules.d/98_auditd_exceptions.rules
    owner: root
    group: root
    mode: 'u-x,go-rwx'
  notify: Restart auditd

- name: POST | AUDITD | Check for auditd differences if reload required
  ansible.builtin.command: augenrules --check
  changed_when: false
  register: discovered_audit_rules_diff

- name: POST | AUDITD | Flush handlers
  ansible.builtin.meta: flush_handlers
