---

- name: "5.3.2.1.1 | PATCH | Ensure password failed attempts lockout is configured"
  when: rhel10cis_rule_5_3_2_1_1
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - pam
    - rule_5.3.2.1.1
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    state: present
    regexp: "^(#|)\\s*deny\\s*=\\s*\\d"
    line: "deny = {{ rhel10cis_pam_faillock_deny }}"

- name: "5.3.2.1.2 | PATCH | Ensure password unlock time is configured"
  when: rhel10cis_rule_5_3_2_1_2
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - pam
    - rule_5.3.2.1.2
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    state: present
    regexp: "^(#|)\\s*unlock_time\\s*=\\s*\\d"
    line: "unlock_time = {{ rhel10cis_pam_faillock_unlock_time }}"

- name: "5.3.2.1.3 | PATCH | Ensure password failed attempts lockout includes root account"
  when: rhel10cis_rule_5_3_2_1_3
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - pam
    - rule_5.3.2.1.3
  ansible.builtin.lineinfile:
    path: /etc/security/faillock.conf
    regexp: "^{{ rhel10cis_pamroot_lock_option }}"
    line: "{{ rhel10cis_pamroot_lock_option }}"
    insertafter: "^# end of pam-auth-update config"
    mode: 'u-x,go-wx'
    create: true
