---

- name: "5.3.1.1 | PATCH | Ensure latest version of pam is installed"
  when: suse15cis_rule_5_3_1_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - pam
    - rule_5.3.1.1
  ansible.builtin.package:
    name: pam
    state: latest
