---
# This is a playbook to test the tasks.
- name: Converge
  hosts: all
  gather_facts: true

  vars:
      current_role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      ansible_user: root
      system_is_container: true

  pre_tasks:
      - name: "Molecule | Fetch the audit output to the controller"
        ansible.builtin.set_fact:
            fetch_audit_output: true
            audit_output_destination: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../_temp_fetched_audits/"

  tasks:
      - name: "Include tasks"
        ansible.builtin.include_role:
            name: "{{ current_role_name }}"
