---

- name: "2.3.3.1 | PATCH | Ensure chrony is configured"
  when: suse15cis_rule_2_3_3_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.3.3.1
    - time
    - chrony
    - NIST800-53R5_AU-3
    - NIST800-53R5_AU-12
  block:
    - name: "2.3.3.1 | PATCH | Ensure chrony is configured | sources"
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/{{ item }}"
        mode: 'go-wx'
        owner: root
        group: root
      loop:
        - etc/chrony.d/pool.conf
        - etc/chrony.d/server.conf
      notify: Restart timeservice

    - name: "2.3.3.1 | PATCH | Ensure chrony is configured | load sources"
      ansible.builtin.lineinfile:
        path: /etc/chrony.conf
        regexp: '^sourcedir /etc/chrony.d'
        line: sourcedir /etc/chrony.d
      notify: Restart timeservice

    - name: "2.3.3.1 | PATCH | Ensure chrony is configured | user chrony"
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/chronyd
        regexp: '^OPTIONS="(?!.* -u chrony.*)(.*)"'
        line: OPTIONS="\1 -u chrony"
        create: true
        backrefs: true
        mode: 'go-wx'

- name: "2.3.3.2 | PATCH | Ensure chrony is enabled and running"
  when: suse15cis_rule_2_3_3_2
  tags:
    - level1-server
    - level1-workstation
    - rule_2.3.3.2
    - time
    - chrony
    - NIST800-53R5_AU-8
  block:
    - name: "2.3.3.2 | PATCH | Ensure chrony is enabled and running"
      ansible.builtin.systemd:
        name: chronyd
        state: started
        enabled: true

    - name: "2.3.3.2 | PATCH | Ensure chrony is enabled and running | disable other time sources | timesyncd"
      when: "'systemd-timesyncd' in ansible_facts.packages"
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: stopped
        enabled: false
        masked: true

    - name: "2.3.3.2 | PATCH | Ensure chrony is enabled and running | disable other time sources | ntpd"
      when: "'ntpd' in ansible_facts.packages"
      ansible.builtin.systemd:
        name: ntpd
        state: stopped
        enabled: false
        masked: true
