---

- name: "1.5.1 | PATCH | Ensure address space layout randomization (ASLR) is enabled | Set active kernel parameter"
  when: suse15cis_rule_1_5_1
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.5.1
    - NIST800-53R5_CM-6
    - aslr
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    sysctl_file: "{{ suse15cis_sysctl_kernel_conf }}"
    reload: true
    sysctl_set: true
    ignoreerrors: true

- name: "1.5.2 | PATCH | Ensure ptrace_scope is restricted"
  when: suse15cis_rule_1_5_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.5.2
    - NIST800-53R5_CM-6
    - ptrace
  ansible.posix.sysctl:
    name: kernel.yama.ptrace_scope
    value: "{{ suse15_ptrace_value }}"
    state: present
    sysctl_file: "{{ suse15cis_sysctl_kernel_conf }}"
    reload: true
    sysctl_set: true
    ignoreerrors: true

- name: "1.5.3 | PATCH | Ensure core dumps are restricted"
  when: suse15cis_rule_1_5_3
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.5.3
    - NIST800-53R5_CM-6
    - coredump
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: ^ProcessSizeMax
    line: ProcessSizeMax=0
    create: true
    owner: root
    group: root
    mode: '0644'

- name: "1.5.4 | PATCH | Ensure prelink is not installed"
  when: suse15cis_rule_1_5_4
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_1.5.4
    - NIST800-53R5_CM-1
    - NIST800-53R5_CM-3
    - NIST800-53R5_CM-6
    - prelink
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: ^Storage
    line: Storage=none
    create: true
    owner: root
    group: root
    mode: '0644'
