---

- name: "SECTION | 4.1 | Configure firewall utility"
  when: not system_is_container
  ansible.builtin.import_tasks:
    file: cis_4.1.x.yml

- name: "SECTION | 4.2 | Configure firewalld"
  when: not system_is_container
  ansible.builtin.import_tasks:
    file: cis_4.2.x.yml
